(cl:defpackage bioloid_hardware-srv
  (:use )
  (:export
   "VREPGETOBSTACLES"
   "<VREPGETOBSTACLES-REQUEST>"
   "VREPGETOBSTACLES-REQUEST"
   "<VREPGETOBSTACLES-RESPONSE>"
   "VREPGETOBSTACLES-RESPONSE"
   "VREPGETSIMSTATE"
   "<VREPGETSIMSTATE-REQUEST>"
   "VREPGETSIMSTATE-REQUEST"
   "<VREPGETSIMSTATE-RESPONSE>"
   "VREPGETSIMSTATE-RESPONSE"
   "VREPSETJOINTTRAJECTORY"
   "<VREPSETJOINTTRAJECTORY-REQUEST>"
   "VREPSETJOINTTRAJECTORY-REQUEST"
   "<VREPSETJOINTTRAJECTORY-RESPONSE>"
   "VREPSETJOINTTRAJECTORY-RESPONSE"
   "VREPSETSIMSTATE"
   "<VREPSETSIMSTATE-REQUEST>"
   "VREPSETSIMSTATE-REQUEST"
   "<VREPSETSIMSTATE-RESPONSE>"
   "VREPSETSIMSTATE-RESPONSE"
  ))

