// Generated by gencpp from file bioloid_hardware/VrepGetSimStateRequest.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPGETSIMSTATEREQUEST_H
#define BIOLOID_HARDWARE_MESSAGE_VREPGETSIMSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bioloid_hardware
{
template <class ContainerAllocator>
struct VrepGetSimStateRequest_
{
  typedef VrepGetSimStateRequest_<ContainerAllocator> Type;

  VrepGetSimStateRequest_()
    : dummy(0)  {
    }
  VrepGetSimStateRequest_(const ContainerAllocator& _alloc)
    : dummy(0)  {
  (void)_alloc;
    }



   typedef int32_t _dummy_type;
  _dummy_type dummy;





  typedef boost::shared_ptr< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VrepGetSimStateRequest_

typedef ::bioloid_hardware::VrepGetSimStateRequest_<std::allocator<void> > VrepGetSimStateRequest;

typedef boost::shared_ptr< ::bioloid_hardware::VrepGetSimStateRequest > VrepGetSimStateRequestPtr;
typedef boost::shared_ptr< ::bioloid_hardware::VrepGetSimStateRequest const> VrepGetSimStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bioloid_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bioloid_hardware': ['/home/francisco/robotis_ws/src/ros-bioloid-gp/src/bioloid_hardware/msg'], 'vision_msgs': ['/opt/ros/melodic/share/vision_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da6c21c6d030841e7157c3016b0292a3";
  }

  static const char* value(const ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda6c21c6d030841eULL;
  static const uint64_t static_value2 = 0x7157c3016b0292a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioloid_hardware/VrepGetSimStateRequest";
  }

  static const char* value(const ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 dummy\n"
;
  }

  static const char* value(const ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dummy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VrepGetSimStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioloid_hardware::VrepGetSimStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "dummy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dummy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPGETSIMSTATEREQUEST_H
