// Generated by gencpp from file bioloid_hardware/VrepSetSimStateRequest.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATEREQUEST_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bioloid_hardware
{
template <class ContainerAllocator>
struct VrepSetSimStateRequest_
{
  typedef VrepSetSimStateRequest_<ContainerAllocator> Type;

  VrepSetSimStateRequest_()
    : operation(0)  {
    }
  VrepSetSimStateRequest_(const ContainerAllocator& _alloc)
    : operation(0)  {
  (void)_alloc;
    }



   typedef int32_t _operation_type;
  _operation_type operation;



  enum {
    SIM_START = 0,
    SIM_STOP = 1,
  };


  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VrepSetSimStateRequest_

typedef ::bioloid_hardware::VrepSetSimStateRequest_<std::allocator<void> > VrepSetSimStateRequest;

typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateRequest > VrepSetSimStateRequestPtr;
typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateRequest const> VrepSetSimStateRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bioloid_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bioloid_hardware': ['/home/francisco/robotis_ws/src/ros-bioloid-gp/src/bioloid_hardware/msg'], 'vision_msgs': ['/opt/ros/melodic/share/vision_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27c5e4a1048c143b919affa90d585d08";
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27c5e4a1048c143bULL;
  static const uint64_t static_value2 = 0x919affa90d585d08ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioloid_hardware/VrepSetSimStateRequest";
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 operation\n"
"int32 SIM_START = 0\n"
"int32 SIM_STOP = 1\n"
;
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VrepSetSimStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioloid_hardware::VrepSetSimStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "operation: ";
    Printer<int32_t>::stream(s, indent + "  ", v.operation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATEREQUEST_H
