// Generated by gencpp from file bioloid_hardware/VrepGetSimState.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPGETSIMSTATE_H
#define BIOLOID_HARDWARE_MESSAGE_VREPGETSIMSTATE_H

#include <ros/service_traits.h>


#include <bioloid_hardware/VrepGetSimStateRequest.h>
#include <bioloid_hardware/VrepGetSimStateResponse.h>


namespace bioloid_hardware
{

struct VrepGetSimState
{

typedef VrepGetSimStateRequest Request;
typedef VrepGetSimStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VrepGetSimState
} // namespace bioloid_hardware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bioloid_hardware::VrepGetSimState > {
  static const char* value()
  {
    return "090b1ecdfa88ad0b24f5bc475c9bd86c";
  }

  static const char* value(const ::bioloid_hardware::VrepGetSimState&) { return value(); }
};

template<>
struct DataType< ::bioloid_hardware::VrepGetSimState > {
  static const char* value()
  {
    return "bioloid_hardware/VrepGetSimState";
  }

  static const char* value(const ::bioloid_hardware::VrepGetSimState&) { return value(); }
};


// service_traits::MD5Sum< ::bioloid_hardware::VrepGetSimStateRequest> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepGetSimState > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepGetSimStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepGetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetSimStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepGetSimStateRequest> should match 
// service_traits::DataType< ::bioloid_hardware::VrepGetSimState > 
template<>
struct DataType< ::bioloid_hardware::VrepGetSimStateRequest>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepGetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetSimStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bioloid_hardware::VrepGetSimStateResponse> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepGetSimState > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepGetSimStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepGetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetSimStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepGetSimStateResponse> should match 
// service_traits::DataType< ::bioloid_hardware::VrepGetSimState > 
template<>
struct DataType< ::bioloid_hardware::VrepGetSimStateResponse>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepGetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetSimStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPGETSIMSTATE_H
