// Generated by gencpp from file bioloid_hardware/VrepSetJointTrajectory.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORY_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORY_H

#include <ros/service_traits.h>


#include <bioloid_hardware/VrepSetJointTrajectoryRequest.h>
#include <bioloid_hardware/VrepSetJointTrajectoryResponse.h>


namespace bioloid_hardware
{

struct VrepSetJointTrajectory
{

typedef VrepSetJointTrajectoryRequest Request;
typedef VrepSetJointTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VrepSetJointTrajectory
} // namespace bioloid_hardware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bioloid_hardware::VrepSetJointTrajectory > {
  static const char* value()
  {
    return "b9e165befafe1cf891b356b2cd8f6e3f";
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectory&) { return value(); }
};

template<>
struct DataType< ::bioloid_hardware::VrepSetJointTrajectory > {
  static const char* value()
  {
    return "bioloid_hardware/VrepSetJointTrajectory";
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::bioloid_hardware::VrepSetJointTrajectoryRequest> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepSetJointTrajectory > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepSetJointTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepSetJointTrajectory >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepSetJointTrajectoryRequest> should match 
// service_traits::DataType< ::bioloid_hardware::VrepSetJointTrajectory > 
template<>
struct DataType< ::bioloid_hardware::VrepSetJointTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepSetJointTrajectory >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bioloid_hardware::VrepSetJointTrajectoryResponse> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepSetJointTrajectory > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepSetJointTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepSetJointTrajectory >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepSetJointTrajectoryResponse> should match 
// service_traits::DataType< ::bioloid_hardware::VrepSetJointTrajectory > 
template<>
struct DataType< ::bioloid_hardware::VrepSetJointTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepSetJointTrajectory >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORY_H
