// Generated by gencpp from file bioloid_hardware/VrepState.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSTATE_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bioloid_hardware
{
template <class ContainerAllocator>
struct VrepState_
{
  typedef VrepState_<ContainerAllocator> Type;

  VrepState_()
    : vrep_state(0)
    , action_state(0)  {
    }
  VrepState_(const ContainerAllocator& _alloc)
    : vrep_state(0)
    , action_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _vrep_state_type;
  _vrep_state_type vrep_state;

   typedef int32_t _action_state_type;
  _action_state_type action_state;



  enum {
    SIM_STOPPED = 0,
    SIM_RUNNING = 1,
    READY_FOR_ACTION = 0,
    ACTION_RUNNING = 1,
  };


  typedef boost::shared_ptr< ::bioloid_hardware::VrepState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioloid_hardware::VrepState_<ContainerAllocator> const> ConstPtr;

}; // struct VrepState_

typedef ::bioloid_hardware::VrepState_<std::allocator<void> > VrepState;

typedef boost::shared_ptr< ::bioloid_hardware::VrepState > VrepStatePtr;
typedef boost::shared_ptr< ::bioloid_hardware::VrepState const> VrepStateConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioloid_hardware::VrepState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioloid_hardware::VrepState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bioloid_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bioloid_hardware': ['/home/francisco/robotis_ws/src/ros-bioloid-gp/src/bioloid_hardware/msg'], 'vision_msgs': ['/opt/ros/melodic/share/vision_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioloid_hardware::VrepState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d63861455531e6f74503f4566b260146";
  }

  static const char* value(const ::bioloid_hardware::VrepState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd63861455531e6f7ULL;
  static const uint64_t static_value2 = 0x4503f4566b260146ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioloid_hardware::VrepState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioloid_hardware/VrepState";
  }

  static const char* value(const ::bioloid_hardware::VrepState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioloid_hardware::VrepState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# vrep start/stop\n"
"int32 vrep_state\n"
"int32 SIM_STOPPED = 0\n"
"int32 SIM_RUNNING = 1\n"
"\n"
"# vrep action state\n"
"int32 action_state\n"
"int32 READY_FOR_ACTION = 0\n"
"int32 ACTION_RUNNING = 1\n"
;
  }

  static const char* value(const ::bioloid_hardware::VrepState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioloid_hardware::VrepState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vrep_state);
      stream.next(m.action_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VrepState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioloid_hardware::VrepState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioloid_hardware::VrepState_<ContainerAllocator>& v)
  {
    s << indent << "vrep_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vrep_state);
    s << indent << "action_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSTATE_H
