// Generated by gencpp from file bioloid_hardware/VrepGetObstacles.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPGETOBSTACLES_H
#define BIOLOID_HARDWARE_MESSAGE_VREPGETOBSTACLES_H

#include <ros/service_traits.h>


#include <bioloid_hardware/VrepGetObstaclesRequest.h>
#include <bioloid_hardware/VrepGetObstaclesResponse.h>


namespace bioloid_hardware
{

struct VrepGetObstacles
{

typedef VrepGetObstaclesRequest Request;
typedef VrepGetObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VrepGetObstacles
} // namespace bioloid_hardware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bioloid_hardware::VrepGetObstacles > {
  static const char* value()
  {
    return "426cd5f67aa6396d3bc5bc91413d573b";
  }

  static const char* value(const ::bioloid_hardware::VrepGetObstacles&) { return value(); }
};

template<>
struct DataType< ::bioloid_hardware::VrepGetObstacles > {
  static const char* value()
  {
    return "bioloid_hardware/VrepGetObstacles";
  }

  static const char* value(const ::bioloid_hardware::VrepGetObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::bioloid_hardware::VrepGetObstaclesRequest> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepGetObstacles > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepGetObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepGetObstacles >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepGetObstaclesRequest> should match 
// service_traits::DataType< ::bioloid_hardware::VrepGetObstacles > 
template<>
struct DataType< ::bioloid_hardware::VrepGetObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepGetObstacles >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bioloid_hardware::VrepGetObstaclesResponse> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepGetObstacles > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepGetObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepGetObstacles >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepGetObstaclesResponse> should match 
// service_traits::DataType< ::bioloid_hardware::VrepGetObstacles > 
template<>
struct DataType< ::bioloid_hardware::VrepGetObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepGetObstacles >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepGetObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPGETOBSTACLES_H
