// Generated by gencpp from file bioloid_hardware/VrepSetSimStateResponse.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATERESPONSE_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bioloid_hardware
{
template <class ContainerAllocator>
struct VrepSetSimStateResponse_
{
  typedef VrepSetSimStateResponse_<ContainerAllocator> Type;

  VrepSetSimStateResponse_()
    : result(0)
    , err_msg()  {
    }
  VrepSetSimStateResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , err_msg(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _err_msg_type;
  _err_msg_type err_msg;



  enum {
    OK = 0,
    ERROR = 1,
  };


  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VrepSetSimStateResponse_

typedef ::bioloid_hardware::VrepSetSimStateResponse_<std::allocator<void> > VrepSetSimStateResponse;

typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateResponse > VrepSetSimStateResponsePtr;
typedef boost::shared_ptr< ::bioloid_hardware::VrepSetSimStateResponse const> VrepSetSimStateResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bioloid_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bioloid_hardware': ['/home/francisco/robotis_ws/src/ros-bioloid-gp/src/bioloid_hardware/msg'], 'vision_msgs': ['/opt/ros/melodic/share/vision_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c52e0efc9e949f620ee0e57623765f9";
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c52e0efc9e949f6ULL;
  static const uint64_t static_value2 = 0x20ee0e57623765f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioloid_hardware/VrepSetSimStateResponse";
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"int32 OK = 0\n"
"int32 ERROR = 1\n"
"string err_msg\n"
;
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.err_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VrepSetSimStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioloid_hardware::VrepSetSimStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "err_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.err_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATERESPONSE_H
