// Generated by gencpp from file bioloid_hardware/VrepSetJointTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORYREQUEST_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace bioloid_hardware
{
template <class ContainerAllocator>
struct VrepSetJointTrajectoryRequest_
{
  typedef VrepSetJointTrajectoryRequest_<ContainerAllocator> Type;

  VrepSetJointTrajectoryRequest_()
    : trajectory()
    , duration(0.0)  {
    }
  VrepSetJointTrajectoryRequest_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VrepSetJointTrajectoryRequest_

typedef ::bioloid_hardware::VrepSetJointTrajectoryRequest_<std::allocator<void> > VrepSetJointTrajectoryRequest;

typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryRequest > VrepSetJointTrajectoryRequestPtr;
typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryRequest const> VrepSetJointTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bioloid_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bioloid_hardware': ['/home/francisco/robotis_ws/src/ros-bioloid-gp/src/bioloid_hardware/msg'], 'vision_msgs': ['/opt/ros/melodic/share/vision_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e14b8bdeed658befb374f7e7b145be1";
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e14b8bdeed658beULL;
  static const uint64_t static_value2 = 0xfb374f7e7b145be1ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioloid_hardware/VrepSetJointTrajectoryRequest";
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectory trajectory\n"
"float64 duration\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VrepSetJointTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioloid_hardware::VrepSetJointTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORYREQUEST_H
