// Generated by gencpp from file bioloid_hardware/VrepSetSimState.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATE_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATE_H

#include <ros/service_traits.h>


#include <bioloid_hardware/VrepSetSimStateRequest.h>
#include <bioloid_hardware/VrepSetSimStateResponse.h>


namespace bioloid_hardware
{

struct VrepSetSimState
{

typedef VrepSetSimStateRequest Request;
typedef VrepSetSimStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VrepSetSimState
} // namespace bioloid_hardware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bioloid_hardware::VrepSetSimState > {
  static const char* value()
  {
    return "058b8c1320f490e738017374cc564f52";
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimState&) { return value(); }
};

template<>
struct DataType< ::bioloid_hardware::VrepSetSimState > {
  static const char* value()
  {
    return "bioloid_hardware/VrepSetSimState";
  }

  static const char* value(const ::bioloid_hardware::VrepSetSimState&) { return value(); }
};


// service_traits::MD5Sum< ::bioloid_hardware::VrepSetSimStateRequest> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepSetSimState > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepSetSimStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepSetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetSimStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepSetSimStateRequest> should match 
// service_traits::DataType< ::bioloid_hardware::VrepSetSimState > 
template<>
struct DataType< ::bioloid_hardware::VrepSetSimStateRequest>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepSetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetSimStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bioloid_hardware::VrepSetSimStateResponse> should match 
// service_traits::MD5Sum< ::bioloid_hardware::VrepSetSimState > 
template<>
struct MD5Sum< ::bioloid_hardware::VrepSetSimStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bioloid_hardware::VrepSetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetSimStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bioloid_hardware::VrepSetSimStateResponse> should match 
// service_traits::DataType< ::bioloid_hardware::VrepSetSimState > 
template<>
struct DataType< ::bioloid_hardware::VrepSetSimStateResponse>
{
  static const char* value()
  {
    return DataType< ::bioloid_hardware::VrepSetSimState >::value();
  }
  static const char* value(const ::bioloid_hardware::VrepSetSimStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSETSIMSTATE_H
