// Generated by gencpp from file bioloid_hardware/VrepSetJointTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORYRESPONSE_H
#define BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bioloid_hardware
{
template <class ContainerAllocator>
struct VrepSetJointTrajectoryResponse_
{
  typedef VrepSetJointTrajectoryResponse_<ContainerAllocator> Type;

  VrepSetJointTrajectoryResponse_()
    : result(0)  {
    }
  VrepSetJointTrajectoryResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;



  enum {
    OK = 0,
    ERROR = 1,
  };


  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VrepSetJointTrajectoryResponse_

typedef ::bioloid_hardware::VrepSetJointTrajectoryResponse_<std::allocator<void> > VrepSetJointTrajectoryResponse;

typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryResponse > VrepSetJointTrajectoryResponsePtr;
typedef boost::shared_ptr< ::bioloid_hardware::VrepSetJointTrajectoryResponse const> VrepSetJointTrajectoryResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bioloid_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bioloid_hardware': ['/home/francisco/robotis_ws/src/ros-bioloid-gp/src/bioloid_hardware/msg'], 'vision_msgs': ['/opt/ros/melodic/share/vision_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f96ebdf6e47df1690ced1ed07e5ae3da";
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf96ebdf6e47df169ULL;
  static const uint64_t static_value2 = 0x0ced1ed07e5ae3daULL;
};

template<class ContainerAllocator>
struct DataType< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioloid_hardware/VrepSetJointTrajectoryResponse";
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"int32 OK = 0\n"
"int32 ERROR = 1\n"
;
  }

  static const char* value(const ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VrepSetJointTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioloid_hardware::VrepSetJointTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOLOID_HARDWARE_MESSAGE_VREPSETJOINTTRAJECTORYRESPONSE_H
